spring:
  application:
    name: used-market-crawler-demo

server:
  port: 8080

used-market-crawler:
  daangn:
    enabled: true
    base-url: https://www.daangn.com
    connect-timeout: 5s
    request-timeout: 10s

  joongna:
    enabled: true
    base-url: https://web.joongna.com
    connect-timeout: 5s
    request-timeout: 10s

  bunjang:
    enabled: true
    base-url: https://api.bunjang.co.kr
    web-base-url: https://m.bunjang.co.kr
    connect-timeout: 5s
    request-timeout: 10s
    user-agent: used-market-crawler/0.1
    image-resolution: 300