plugins {
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom(
            org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
        )
    }
}

dependencies {
    api project(':crawler-core')
    api project(':crawler-provider-daangn')
    api project(':crawler-provider-joongna')
    api project(':crawler-provider-bunjang')

    implementation 'org.springframework.boot:spring-boot-autoconfigure'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}